[program:ibolt-drac-medium-T3-20260926]
command=/bin/bash /workspace/optiq-drac-parallel-20260926/pointmaze_experiments/parallel.sh 0 medium 3
autostart=false
autorestart=false
stopasgroup=true
killasgroup=true
stdout_logfile=/workspace/ibolt-drac-medium-T3-20260926.log
redirect_stderr=true

[program:ibolt-drac-hard-T3-20260926]
command=/bin/bash /workspace/optiq-drac-parallel-20260926/pointmaze_experiments/parallel.sh 1 hard 3
autostart=false
autorestart=false
stopasgroup=true
killasgroup=true
stdout_logfile=/workspace/ibolt-drac-hard-T3-20260926.log
redirect_stderr=true

[program:ibolt-drac-medium-T5-20260926]
command=/bin/bash /workspace/optiq-drac-parallel-20260926/pointmaze_experiments/parallel.sh 2 medium 5
autostart=false
autorestart=false
stopasgroup=true
killasgroup=true
stdout_logfile=/workspace/ibolt-drac-medium-T5-20260926.log
redirect_stderr=true

[program:ibolt-drac-hard-T5-20260926]
command=/bin/bash /workspace/optiq-drac-parallel-20260926/pointmaze_experiments/parallel.sh 3 hard 5
autostart=false
autorestart=false
stopasgroup=true
killasgroup=true
stdout_logfile=/workspace/ibolt-drac-hard-T5-20260926.log
redirect_stderr=true
