[program:optiq-v2-checked64]
process_name=%(program_name)s-%(process_num)s
numprocs=4
directory=/root/OptiQ
command=/bin/bash /opt/supervisor-scripts/optiq-v2-checked64.sh %(process_num)s
environment=PROC_NAME="%(program_name)s-%(process_num)s"
autostart=false
autorestart=false
startsecs=1
stopwaitsecs=120
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
