"""Read-only rescoring of historical v3 successful paths; not retraining or MC Q truth."""
from pathlib import Path
from datetime import datetime, timezone
import hashlib, importlib.util, json
import numpy as np
ROOT=Path(__file__).resolve().parent
A=ROOT.parent
helper=A/'antmaze_startnorm_geodesic_250k/report_results.py'
spec=importlib.util.spec_from_file_location('frozen_normalized',helper)
m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
R=m.reward
COHORTS={
 'old_euclidean_left':(A/'antmaze_gamma999_retention_1m/results/vast-heechan-180/runs/v3-optiq-gamma999-H0.7-i500-1m-s0/evaluations/0001008384/policy-fixed/rollouts.npz',1),
 'original_geodesic_right':(A/'antmaze_geodesic_gamma999_250k/results/vast-heechan-180/runs/v3-optiq-geodesic-gamma999-H0.7-i500-250k-s0/evaluations/0000258304/policy-fixed/rollouts.npz',2),
 'normalized_T3_right':(A/'antmaze_startnorm_geodesic_250k/results/vast-heechan-180/runs/v3-optiq-startnorm-geodesic-gamma999-T3-H0.7-i500-250k-s0/evaluations/0000258304/policy-fixed/rollouts.npz',2),
}
GAMMAS=(.99,.999,.9999,.99999,1.)
rows=[]; reference=None
for name,(path,goal) in COHORTS.items():
 d=np.load(path); states=d['initial_full_state']
 assert np.array_equal(states,np.repeat(states[:1],len(states),axis=0))
 if reference is None:reference=states[0]
 np.testing.assert_array_equal(states[0],reference)
 assert bool(d['fixed']) and str(d['mode'])=='policy'
 episodes=[]
 for i in np.flatnonzero(d['goals']==goal):
  xy=d['xy'][i,:int(d['lengths'][i])+1].astype(np.float64)
  distance=R.distance(xy,'v3',R.START_NORMALIZED_PROFILE)
  assert distance[-1]<1e-4
  rewards=100*(distance[:-1]-distance[1:])
  np.testing.assert_allclose(rewards.sum(),100*distance[0],atol=.01,rtol=0)
  episodes.append(dict(index=int(i),length=int(d['lengths'][i]),start_distance=float(distance[0]),
   end_distance=float(distance[-1]),scores={str(g):float(rewards@np.power(g,np.arange(len(rewards)))) for g in GAMMAS}))
 rows.append(dict(cohort=name,goal=goal,all_episodes=len(d['goals']),successful_episodes=len(episodes),
  raw_path=str(path),raw_sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
  episodes=episodes,length_mean=float(np.mean([e['length'] for e in episodes])),
  score_means={str(g):float(np.mean([e['scores'][str(g)] for e in episodes])) for g in GAMMAS}))
result=dict(time_utc=datetime.now(timezone.utc).isoformat(),reward_source=m.SOURCE,
 reward_profile=R.START_NORMALIZED_PROFILE,rows=rows,
 caveats=['Historical paths are generated by different policies/settings/budgets.',
 'Only the reward functional is rescored; these are not new rollouts or calibrated Q targets.',
 'Cohorts condition on success. Original failures remain counted and preserved.',
 'gamma1 is an analytic telescoping reference only; no gamma1 training was launched.'])
(ROOT/'results.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps([{k:v for k,v in r.items() if k not in ('episodes','raw_path')} for r in rows],indent=2))
