# @package _global_
defaults:
  - /v5/final
  - _self_

alg:
  behavior_best_of_k: 8

output_root: ../optiq-experiments/v5_bestof8/outputs
run_name: ${task}-v5-meanOT-bestof8-collect-T${alg.actor.temperature}-eps${alg.actor.sinkhorn_epsilon}-s${seed}
wandb:
  project: v5-jaehoon
  group: ${env_name}_v5_meanOT_bestof8_collect_T${alg.actor.temperature}_eps${alg.actor.sinkhorn_epsilon}
  job_type: v5-bestof8-collection
